/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#454748",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#474646",
        "on-error": "#ffffff",
        "surface-tint": "#5f5e5e",
        "error-container": "#ffdad6",
        "primary-fixed": "#e5e2e1",
        "surface-bright": "#f9f9ff",
        "on-surface": "#151c27",
        "on-secondary-fixed": "#07006c",
        "on-tertiary-fixed": "#191c1d",
        "surface-dim": "#d3daea",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c9c6c5",
        "background": "#f9f9ff",
        "on-surface-variant": "#444748",
        surface: "#f9f9ff",
        "outline-variant": "#c4c7c7",
        "on-background": "#151c27",
        "surface-container-high": "#e2e8f8",
        outline: "#747878",
        "on-secondary-container": "#fffbff",
        "on-primary-container": "#858383",
        primary: "#000000",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-variant": "#dce2f3",
        "inverse-primary": "#c9c6c5",
        "secondary-container": "#6063ee",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dce2f3",
        "inverse-surface": "#2a313d",
        "surface-container-low": "#f0f3ff",
        "on-tertiary-container": "#828485",
        "primary-container": "#1c1b1b",
        "tertiary-fixed": "#e1e3e4",
        "on-primary-fixed": "#1c1b1b",
        "tertiary-fixed-dim": "#c5c7c8",
        "surface-container": "#e7eefe",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "tertiary-container": "#191c1d",
        secondary: "#4648d4",
        "inverse-on-surface": "#ebf1ff",
        tertiary: "#000000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "64px",
        "stack-md": "16px",
        gutter: "24px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "container-max": "800px",
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg-mobile": [
          "32px",
          {
            lineHeight: "38px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
      },
    },
  },
  plugins: [],
};
